"""add_codes_table_and_entry_code_relationship

Revision ID: 19b40f486dfc
Revises: e6c54a18df58
Create Date: 2026-01-12 15:48:34.742292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19b40f486dfc'
down_revision: Union[str, None] = 'e6c54a18df58'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('codes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('product_id', sa.String(length=100), nullable=True),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('used_by_user_id', sa.Integer(), nullable=True),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['used_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_codes_code'), 'codes', ['code'], unique=True)
    op.create_index(op.f('ix_codes_id'), 'codes', ['id'], unique=False)
    op.create_index(op.f('ix_codes_used'), 'codes', ['used'], unique=False)
    op.add_column('entries', sa.Column('code_id', sa.Integer(), nullable=True))
    op.add_column('entries', sa.Column('code_entered_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'entries', 'codes', ['code_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'entries', type_='foreignkey')
    op.drop_column('entries', 'code_entered_at')
    op.drop_column('entries', 'code_id')
    op.drop_index(op.f('ix_codes_used'), table_name='codes')
    op.drop_index(op.f('ix_codes_id'), table_name='codes')
    op.drop_index(op.f('ix_codes_code'), table_name='codes')
    op.drop_table('codes')
    # ### end Alembic commands ###
