"""add_date_of_birth_and_registration_fields

Revision ID: 833277db66bb
Revises: 19b40f486dfc
Create Date: 2026-01-14 11:06:32.549147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '833277db66bb'
down_revision: Union[str, None] = '19b40f486dfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('otp_verifications', sa.Column('name', sa.String(length=255), nullable=True))
    op.add_column('otp_verifications', sa.Column('date_of_birth', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('date_of_birth', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'date_of_birth')
    op.drop_column('otp_verifications', 'date_of_birth')
    op.drop_column('otp_verifications', 'name')
    # ### end Alembic commands ###
