"""add_fraud_detection_fields

Revision ID: e6c54a18df58
Revises: 
Create Date: 2026-01-12 14:41:23.368991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6c54a18df58'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('entries', sa.Column('hash_ahash', sa.String(length=64), nullable=True))
    op.add_column('entries', sa.Column('hash_dhash', sa.String(length=64), nullable=True))
    op.add_column('entries', sa.Column('hash_whash', sa.String(length=64), nullable=True))
    op.add_column('entries', sa.Column('fraud_score', sa.Float(), nullable=False, server_default='0.0'))
    op.add_column('entries', sa.Column('fraud_reason', sa.Text(), nullable=True))
    op.add_column('entries', sa.Column('similar_entry_ids', sa.Text(), nullable=True))
    op.add_column('entries', sa.Column('review_status', sa.String(length=20), nullable=False, server_default='pending'))
    op.add_column('entries', sa.Column('reviewed_by', sa.Integer(), nullable=True))
    op.add_column('entries', sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_index('ix_entries_image_hash', table_name='entries')
    op.create_index(op.f('ix_entries_image_hash'), 'entries', ['image_hash'], unique=False)
    op.create_index(op.f('ix_entries_fraud_score'), 'entries', ['fraud_score'], unique=False)
    op.create_index(op.f('ix_entries_hash_ahash'), 'entries', ['hash_ahash'], unique=False)
    op.create_index(op.f('ix_entries_hash_dhash'), 'entries', ['hash_dhash'], unique=False)
    op.create_index(op.f('ix_entries_hash_whash'), 'entries', ['hash_whash'], unique=False)
    op.create_index(op.f('ix_entries_review_status'), 'entries', ['review_status'], unique=False)
    op.create_foreign_key(None, 'entries', 'users', ['reviewed_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'entries', type_='foreignkey')
    op.drop_index(op.f('ix_entries_review_status'), table_name='entries')
    op.drop_index(op.f('ix_entries_hash_whash'), table_name='entries')
    op.drop_index(op.f('ix_entries_hash_dhash'), table_name='entries')
    op.drop_index(op.f('ix_entries_hash_ahash'), table_name='entries')
    op.drop_index(op.f('ix_entries_fraud_score'), table_name='entries')
    op.drop_index(op.f('ix_entries_image_hash'), table_name='entries')
    op.create_index('ix_entries_image_hash', 'entries', ['image_hash'], unique=False)
    op.drop_column('entries', 'reviewed_at')
    op.drop_column('entries', 'reviewed_by')
    op.drop_column('entries', 'review_status')
    op.drop_column('entries', 'similar_entry_ids')
    op.drop_column('entries', 'fraud_reason')
    op.drop_column('entries', 'fraud_score')
    op.drop_column('entries', 'hash_whash')
    op.drop_column('entries', 'hash_dhash')
    op.drop_column('entries', 'hash_ahash')
    # ### end Alembic commands ###
